### PR TITLE
Add --start-date and --end-date flags

### PR DESCRIPTION
**Pull request by bronzdoc**
Closes https://github.com/duckinator/inq/issues/281

Hi @duckinator 👋 

This PR adds the `--start-date` and `--end-date` flags to `inq` , this will allow a user to generate a report from a date interval. 

Note that the functionality when using the  `--date` flag is preserved.

### CODE REVIEW

**Comment by bronzdoc** [comment]
I'm having a green build locally, I'm not sure what's happening 😕 I will investigate further tomorrow...

Screen Shot 2020-04-02 at 10 27 52 PM

**Comment by duckinator** [comment]
@bronzdoc the failures are due to #284. Basically, I couldn't get VCR to not cache the GitHub token, so I used a dedicated token, let it get cached, then regenerated the token (but didn't update it, so it always hit the cache). I'm looking into a way to resolve that now. :slightly_smiling_face:

**Comment by bronzdoc** [comment]
Thanks for having a look @duckinator! please let me know if this implementation is ok with you

**Comment by duckinator** [comment]
@bronzdoc your implementation looks fine to me. I also found a fix for #284, but have to wait for GitHub API rate limits to reset before I can regenerate the fixtures. Once the fix is merged I'll explain what you need to do to get tests working. Sorry for the hassle!

**Comment by bronzdoc** [comment]
@duckinator let me know if Is there something I need to do, thanks! 🙇

**Comment by duckinator** [comment]
Hey, sorry about the delay! If you rebase off master, then do `bundle exec rake spec` it should record new fixtures. Commit + push new changes at that point and it should be good. :+1:

**Comment by duckinator** [comment]
bors r+

thanks @bronzdoc! :3

**Pull request merged**
